#!/bin/bash

echo "🔧 GitHub Actions Personal Access Token Setup"
echo "============================================="
echo ""

echo "📋 Steps to fix the permission issue:"
echo ""
echo "1. 🌐 Go to GitHub Settings:"
echo "   https://github.com/settings/tokens"
echo ""
echo "2. 🔑 Create a new Personal Access Token:"
echo "   - Click 'Generate new token (classic)'"
echo "   - Name: 'README Update Token'"
echo "   - Expiration: 90 days (or your preference)"
echo "   - Scopes: Select 'repo' (full control)"
echo "   - Click 'Generate token'"
echo "   - COPY THE TOKEN (you won't see it again!)"
echo ""
echo "3. 🔐 Add Token to Repository Secrets:"
echo "   - Go to: https://github.com/happy-mfv/happy-mfv/settings/secrets/actions"
echo "   - Click 'New repository secret'"
echo "   - Name: PAT_TOKEN"
echo "   - Value: Paste your token"
echo "   - Click 'Add secret'"
echo ""
echo "4. 🚀 Test the Workflow:"
echo "   - Go to: https://github.com/happy-mfv/happy-mfv/actions"
echo "   - Select 'PAT README Update'"
echo "   - Click 'Run workflow'"
echo ""
echo "✅ The workflow will now have proper permissions!"
echo ""
echo "📝 Alternative: Use the Activity Action (no setup needed)"
echo "   - Go to Actions tab"
echo "   - Select 'Update README with Activity'"
echo "   - Click 'Run workflow'"
echo ""
echo "🎯 Recommended: Use the PAT approach for full control" 