name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update README with latest activity'
          MAX_LINES: 5

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          USERNAME: happy-mfv
          THEME: radical 